# Generated by Django 5.0.4 on 2024-12-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.FileField(default='video.mp4', upload_to='video/%Y', verbose_name='Видео'),
            preserve_default=False,
        ),
    ]
